### PR TITLE
Added support for array scopes.

### PR DESCRIPTION
**Pull request by danielbjornadal**
Skoruba IdentityServer add scopes as array, not string. 
This change will support auth0`s string scope and other array scopes.

### CODE REVIEW

**Comment by boyander** [comment]
agree, must support array scopes

**Comment by deammer** [comment]
This is essential with array scopes provided by [`express-jwt`](https://github.com/auth0/express-jwt) as well. @luisrudge could you please merge this soon?

**Comment by luisrudge** [comment]
Can you add some tests? I like the idea, but I can't merge this without tests backing up the solution.

**Comment by deammer** [comment]
@danielbjornadal I don't mind writing those tests if you'd like, just let me know!

**Comment by luisrudge** [comment]
@danielbjornadal if he doesn't answer, feel free to create another PR and I'll close this one.

**Comment by deammer** [comment]
@luisrudge I added tests and another feature in #21.

**Comment by luisrudge** [comment]
fixed in https://github.com/auth0/express-jwt-authz/pull/21

**Pull request closed without merging**
