### PR TITLE
fix express deprecated res.send(status, body)

### PR DESCRIPTION
**Pull request by djom202**
Use res.status(status).send(body) instead node_modules/express-jwt-authz/lib/index.js:2:14

### CODE REVIEW

**Comment by djom202** [comment]
fix express deprecated res.send(status, body)

**Comment by coryhouse** [comment]
Was about to open a PR on this, but see @djom20 beat me to it. Hey @auth0alec @auth0jeffries can we get this merged?

**Comment by auth0jeffries** [comment]
Hi @coryhouse I am not familiar with this repository or project. Is there someone better suited to approving the merge request?

**Comment by coryhouse** [comment]
Well @dschenkelman appears to have created it on behalf of Auth0. Perhaps he left the company? Would be great if someone at Auth0 could review and approve the pending PRs.

**Comment by auth0jeffries** [comment]
@coryhouse I've found him but he appears to be offline this moment. I'll check back up within the day to figure out how to get these changes updated. Thanks for the patience and direction!

**Comment by coryhouse** [comment]
Great, thanks for following up @auth0jeffries. :) Please note that this PR seems to be a duplicate of #5

**Comment by auth0jeffries** [comment]
Hi @coryhouse and @djom20 we are working on getting this ready by the end of the month. There are some additional in-house tasks that also need to be completed for these changes before we can perform the merge. Stay tuned!

**Comment by coryhouse** [comment]
Great to hear. Thanks for the update!

**Comment by luisrudge** [comment]
fixed in https://github.com/auth0/express-jwt-authz/pull/12

**Comment by luisrudge** [comment]
We're just waiting for github to stabilize and CI kick in so we can release an alpha version.

**Pull request closed without merging**
